name: My Medium posts
on:
    schedule:
        # Runs at 9：30pm UTC
        - cron: "30 21 * * *"
    workflow_dispatch:

jobs:
    update-readme-with-blog:
        name: Update this repo's README with all medium posts
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: gautamkrishnar/blog-post-workflow@master
              with:
                  max_post_count: "100"
                  feed_list: "https://medium.com/feed/@molly1024"
